development:
  # Configure available database sessions. (required)
  sessions:
    default:
      uri: mongodb://emsadmin:sigmond123@ds027809.mongolab.com:27809/heroku_app21545321

      #uri: mongodb://heroku_app21545321:v3177svouq4qkc2mu65209bqp6@ds027809.mongolab.com:27809/heroku_app21545321

      options:
        consistency: :strong
    #default:
     # database: app21545321
      #hosts:
       # - localhost:27017
      #options:
       
 # options:
    
test:
  sessions:
    default:
      database: ems
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0

 # mongodb://heroku_app7056684:i49vdi86vsoidg0sn5unrqkf54@ds037387-a.mongolab.com:37387/heroku_app7056684
production:
  sessions:
    default:
      uri: mongodb://emsadmin:Sigmond123!@ds027809.mongolab.com:27809/heroku_app21545321
      #uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        consistency: :strong
